// This file is auto-generated. Do not edit manually.

export interface ChampionData {
  traits: string[];
  championTier: number;
  teamPlannerCode: string;
}

export const championMapping: Record<string, ChampionData> = {
  "Alistar": { traits: ["Golden Ox", "Bruiser"], championTier: 1, teamPlannerCode: "312" },
  "Dr. Mundo": { traits: ["Street Demon", "Bruiser", "Slayer"], championTier: 1, teamPlannerCode: "2e3" },
  "Jax": { traits: ["Exotech", "Bastion"], championTier: 1, teamPlannerCode: "305" },
  "Kindred": { traits: ["Nitro", "Rapidfire", "Marksman"], championTier: 1, teamPlannerCode: "2fb" },
  "Kog'Maw": { traits: ["BoomBot", "Rapidfire"], championTier: 1, teamPlannerCode: "303" },
  "Morgana": { traits: ["Divinicorp", "Dynamo"], championTier: 1, teamPlannerCode: "2ea" },
  "Nidalee": { traits: ["Nitro", "A.M.P"], championTier: 1, teamPlannerCode: "2f9" },
  "Poppy": { traits: ["Cyberboss", "Bastion"], championTier: 1, teamPlannerCode: "308" },
  "Seraphine": { traits: ["Anima Squad", "Techie"], championTier: 1, teamPlannerCode: "2fe" },
  "Shaco": { traits: ["Syndicate", "Slayer"], championTier: 1, teamPlannerCode: "2f0" },
  "Sylas": { traits: ["Anima Squad", "Vanguard"], championTier: 1, teamPlannerCode: "30c" },
  "Vi": { traits: ["Cypher", "Vanguard"], championTier: 1, teamPlannerCode: "310" },
  "Zyra": { traits: ["Street Demon", "Techie"], championTier: 1, teamPlannerCode: "2f7" },
  "Darius": { traits: ["Syndicate", "Bruiser"], championTier: 2, teamPlannerCode: "2e2" },
  "Ekko": { traits: ["Street Demon", "Strategist"], championTier: 2, teamPlannerCode: "31f" },
  "Graves": { traits: ["Golden Ox", "Executioner"], championTier: 2, teamPlannerCode: "315" },
  "Illaoi": { traits: ["Anima Squad", "Bastion"], championTier: 2, teamPlannerCode: "2fd" },
  "Jhin": { traits: ["Exotech", "Marksman", "Dynamo"], championTier: 2, teamPlannerCode: "300" },
  "LeBlanc": { traits: ["Cypher", "Strategist"], championTier: 2, teamPlannerCode: "2e8" },
  "Naafiri": { traits: ["Exotech", "A.M.P"], championTier: 2, teamPlannerCode: "301" },
  "Rhaast": { traits: ["Divinicorp", "Vanguard"], championTier: 2, teamPlannerCode: "317" },
  "Shyvana": { traits: ["Nitro", "Bastion", "Techie"], championTier: 2, teamPlannerCode: "2fa" },
  "Skarner": { traits: ["BoomBot", "Vanguard"], championTier: 2, teamPlannerCode: "304" },
  "Twisted Fate": { traits: ["Syndicate", "Rapidfire"], championTier: 2, teamPlannerCode: "2f1" },
  "Vayne": { traits: ["Anima Squad", "Slayer"], championTier: 2, teamPlannerCode: "30e" },
  "Veigar": { traits: ["Cyberboss", "Techie"], championTier: 2, teamPlannerCode: "2f3" },
  "Braum": { traits: ["Syndicate", "Vanguard"], championTier: 3, teamPlannerCode: "2f8" },
  "Draven": { traits: ["Cypher", "Rapidfire"], championTier: 3, teamPlannerCode: "31c" },
  "Elise": { traits: ["Nitro", "Dynamo"], championTier: 3, teamPlannerCode: "2e4" },
  "Fiddlesticks": { traits: ["BoomBot", "Techie"], championTier: 3, teamPlannerCode: "2e5" },
  "Galio": { traits: ["Cypher", "Bastion"], championTier: 3, teamPlannerCode: "2e6" },
  "Gragas": { traits: ["Divinicorp", "Bruiser"], championTier: 3, teamPlannerCode: "302" },
  "Jarvan IV": { traits: ["Golden Ox", "Vanguard", "Slayer"], championTier: 3, teamPlannerCode: "314" },
  "Jinx": { traits: ["Street Demon", "Marksman"], championTier: 3, teamPlannerCode: "31e" },
  "Mordekaiser": { traits: ["Exotech", "Bruiser", "Techie"], championTier: 3, teamPlannerCode: "311" },
  "Rengar": { traits: ["Street Demon", "Executioner"], championTier: 3, teamPlannerCode: "2ed" },
  "Senna": { traits: ["Divinicorp", "Slayer"], championTier: 3, teamPlannerCode: "2ef" },
  "Varus": { traits: ["Exotech", "Executioner"], championTier: 3, teamPlannerCode: "2f2" },
  "Yuumi": { traits: ["Anima Squad", "A.M.P", "Strategist"], championTier: 3, teamPlannerCode: "2fc" },
  "Annie": { traits: ["Golden Ox", "A.M.P"], championTier: 4, teamPlannerCode: "316" },
  "Aphelios": { traits: ["Golden Ox", "Marksman"], championTier: 4, teamPlannerCode: "71a" },
  "Brand": { traits: ["Street Demon", "Techie"], championTier: 4, teamPlannerCode: "2e1" },
  "Cho'Gath": { traits: ["BoomBot", "Bruiser"], championTier: 4, teamPlannerCode: "30a" },
  "Leona": { traits: ["Anima Squad", "Vanguard"], championTier: 4, teamPlannerCode: "30f" },
  "Miss Fortune": { traits: ["Syndicate", "Dynamo"], championTier: 4, teamPlannerCode: "2e9" },
  "Neeko": { traits: ["Street Demon", "Strategist"], championTier: 4, teamPlannerCode: "2eb" },
  "Sejuani": { traits: ["Exotech", "Bastion"], championTier: 4, teamPlannerCode: "307" },
  "Vex": { traits: ["Divinicorp", "Executioner"], championTier: 4, teamPlannerCode: "2f4" },
  "Xayah": { traits: ["Anima Squad", "Marksman"], championTier: 4, teamPlannerCode: "2ff" },
  "Zed": { traits: ["Cypher", "Divinicorp"], championTier: 4, teamPlannerCode: "2f5" },
  "Zeri": { traits: ["Exotech", "Rapidfire"], championTier: 4, teamPlannerCode: "2f6" },
  "Ziggs": { traits: ["Cyberboss", "Strategist"], championTier: 4, teamPlannerCode: "309" },
  "Aurora": { traits: ["Anima Squad", "Dynamo"], championTier: 5, teamPlannerCode: "30d" },
  "Kobuko": { traits: ["Cyberboss", "Bruiser"], championTier: 5, teamPlannerCode: "306" },
  "Renekton": { traits: ["Divinicorp", "Bastion"], championTier: 5, teamPlannerCode: "2ec" },
  "Samira": { traits: ["Street Demon", "A.M.P"], championTier: 5, teamPlannerCode: "2ee" },
  "Urgot": { traits: ["BoomBot", "Executioner"], championTier: 5, teamPlannerCode: "30b" },
  "Viego": { traits: ["Golden Ox", "Techie"], championTier: 5, teamPlannerCode: "313" },
};

export const traitThresholds: Record<string, number> = {
  "Anima Squad": 3,
  "BoomBot": 2,
  "Cyberboss": 2,
  "Cypher": 3,
  "Divinicorp": 1,
  "Exotech": 3,
  "Golden Ox": 2,
  "Nitro": 3,
  "Street Demon": 3,
  "Syndicate": 3,
  "A.M.P": 2,
  "Bastion": 2,
  "Bruiser": 2,
  "Dynamo": 2,
  "Executioner": 2,
  "Marksman": 2,
  "Rapidfire": 2,
  "Slayer": 2,
  "Strategist": 2,
  "Techie": 2,
  "Vanguard": 2,
};
